name: Deploy on Main Branch Update

# Defines when the action should run. 
on:
  push:
    branches:
      - main  # Specifies the main branch

# Defines the jobs to run
jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the type of machine to run the job on

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false 
    
    - name: Setup Git identity
      run: |
        git config --local user.email "masterupvcup@gmail.com"
        git config --local user.name "Master upv cup"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you need

    - name: Install PNPM
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install
    
    - name: Add GitHub Token for Authentication
      run: git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/masterupvcup/website.git

    - name: Deploy
      run: pnpm run deploy
      # env:
        # Set any environment variables needed for deployment
        # For example:
        # MY_SECRET: ${{ secrets.MY_SECRET }}
